# $schema: "https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json"
name: "acmeproxy"

services:
  acmeproxy:
    image: ghcr.io/1e04/acmeproxy.pl
    restart: unless-stopped
    ports: # Or use expose when using a reverse proxy
      - 9443:9443
    volumes:
      - ./config:/config:rw
      # Optionally store the generated certificate data on a persistent volume
      # - ./cert-data:/cert-data:rw
